### PR TITLE
Removed the proto files

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**
Removed the proto files as requested by Alex.

### CODE REVIEW

**Review by mustafapylons — APPROVED** [review]
Looks like they are all removed. It's fine with me.

**Comment by MikeSofaer** [comment]
We still have the current active proto files?

**Comment by Tiny-Angel305** [comment]
Well, removing protos doesn't make much sense to me. Dart-sdk is public to lots of Pylons app developers. So I think it'd be better to allow them to try generating Dart codes based on proto files themselves. They can't get required protos from anywhere else this repository, as `Pylons` and `flutter-wallet` are both private AFAIK?

I'd propose to remove unused protos only and have active protos still in this repo, and we must care about keeping the sdk synced with the `flutter-wallet` regarding any further protocol changes.

**Comment by MikeSofaer** [comment]
> Well, removing protos doesn't make much sense to me. Dart-sdk is public to lots of Pylons app developers. So I think it'd be better to allow them to try generating Dart codes based on proto files themselves. They can't get required protos from anywhere else this repository, as `Pylons` and `flutter-wallet` are both private AFAIK?
> 
> I'd propose to remove unused protos only and have active protos still in this repo, and we must care about keeping the sdk synced with the `flutter-wallet` regarding any further protocol changes.

I agree with this

**Comment by afti-githobo** [comment]
Is there a sane way to handle obtaining dependencies for our protos and keeping things limited to only the active ones, or does that have to be done by hand?

**Comment by kjawadDeveloper2** [comment]
Its a dart sdk. No one who will be using this repo will be looking at the proto files.

**Comment by afti-githobo** [comment]
I think that's basically a fair assessment, but the concern over keeping our protos publically accessible somehow isn't misplaced, either. The better option, though, would probably be creating a separate public `pylons_protos` repo?

**Comment by MikeSofaer** [comment]
> I think that's basically a fair assessment, but the concern over keeping our protos publically accessible somehow isn't misplaced, either. The better option, though, would probably be creating a separate public `pylons_protos` repo?

We could do that, but this is the repo that needs updating when the protos change anyway, so adding another repo to the flow seems like maybe it could get dropped.

**Comment by afti-githobo** [comment]
That's valid, and set me to looking around for a decent solution that addresses both 'how do we keep from dropping the protos' and 'how do we remove clutter in this repo' while keeping our protos accessible, ideally w/o having to just manually handle all our dependencies.

At a cursory glance, [https://github.com/stormcat24/protodep](protodep) seems like what we need? We migrate just-the-Pylons-protos to `pylons-protos` or what have you, write a `protodep.toml` and a quick and nasty proto rebuild script for this repo, gitignore the actual protos path, and we've established a sane, portable workflow for using the Pylons protos that other developers can easily adapt to their own needs. Importantly, this workflow would make it _impossible_ for us to drop the protos repository if we put it into use on the Go side as well; there'd be a single source of truth for the Pylons protos.

Does this seem like a reasonable thing to pursue?

**Comment by mustafapylons** [comment]
@afti-githobo This makes sense to me. If @MikeSofaer  agrees and no other objections, let's go ahead.

**Comment by MikeSofaer** [comment]
Happy to let the team decide how to do it, as long as people have a way to get what they need

**Pull request merged**
