### PR TITLE
adding cookbook, recipe, and query docs to sdk

### PR DESCRIPTION
**Pull request by mijolae**
Adding Cookbook, Recipe and Query explanation to docs.

### CODE REVIEW

**Comment by kjawadDeveloper2** [comment]
@mijolae  its not complete right?

**Comment by mijolae** [comment]
it is a draft if you guys think that there is anything wrong with it, but complete if the info is good and what we were striving for.

**Review by aljo242 — CHANGES_REQUESTED** [review]
Writing looks good to me as a starting point.

I don't think we need the additional folder `spec` in the layout, since these files are more like "tutorials" than "specifications".

**Comment by mijolae** [comment]
okie updated the folder

**Review by aljo242 — APPROVED** [review]
Thanks! lgtm

**Comment by kjawadDeveloper2** [comment]
@mijolae  i think we need more info in it.

**Comment by mijolae** [comment]
@kjawadDeveloper what info do you suggest? we can add it

**Comment by kjawadDeveloper2** [comment]
How to create an NFT application a simple flow in terms of the methods we exposed.

**Comment by mijolae** [comment]
running one last check and from there we can merge!

**Pull request merged**
