### PR TITLE
updating README.md for a better readibility.

### PR DESCRIPTION
**Pull request by mijolae**
added some formatting for new devs to have a better experience with onboarding.

### CODE REVIEW

**Comment by afti-githobo** [comment]
I made an additional commit to make some more changes, but I think it's good now?

**Review by kjawadDeveloper2 — APPROVED** [review]
Looks Good from myside.

**Comment by kjawadDeveloper2** [comment]
@mustafapylons  and @aljo242  whats your thought on this.

**Review by aljo242 — APPROVED** [review]
Looks a lot better to me

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Pull request merged**
